# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bag.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
import messages_pb2 as messages__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='bag.proto',
  package='bag',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\tbag.proto\x12\x03\x62\x61g\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x0emessages.proto\"c\n\x03\x42\x61g\x12-\n\ttimestamp\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12-\n\x08messages\x18\x02 \x03(\x0b\x32\x1b.ai.flow.android.ZMQMessageb\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,messages__pb2.DESCRIPTOR,])




_BAG = _descriptor.Descriptor(
  name='Bag',
  full_name='bag.Bag',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='bag.Bag.timestamp', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='messages', full_name='bag.Bag.messages', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=166,
)

_BAG.fields_by_name['timestamp'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_BAG.fields_by_name['messages'].message_type = messages__pb2._ZMQMESSAGE
DESCRIPTOR.message_types_by_name['Bag'] = _BAG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Bag = _reflection.GeneratedProtocolMessageType('Bag', (_message.Message,), {
  'DESCRIPTOR' : _BAG,
  '__module__' : 'bag_pb2'
  # @@protoc_insertion_point(class_scope:bag.Bag)
  })
_sym_db.RegisterMessage(Bag)


# @@protoc_insertion_point(module_scope)
