# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: camera_intrinsics.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='camera_intrinsics.proto',
  package='ai.flow.android',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x17\x63\x61mera_intrinsics.proto\x12\x0f\x61i.flow.android\"\xe8\x02\n\x10\x43\x61meraIntrinsics\x12\x11\n\ttimestamp\x18\x01 \x01(\x03\x12 \n\x18physical_focal_length_mm\x18\x02 \x01(\x02\x12\x17\n\x0fsensor_width_mm\x18\x03 \x01(\x02\x12\x18\n\x10sensor_height_mm\x18\x04 \x01(\x02\x12\x1a\n\x12\x61\x63tive_array_width\x18\x05 \x01(\x05\x12\x1b\n\x13\x61\x63tive_array_height\x18\x06 \x01(\x05\x12\x1f\n\x17\x64istortion_coefficients\x18\x07 \x03(\x02\x12\x1d\n\x15intrinsic_calibration\x18\x08 \x03(\x02\x12\x17\n\x0f\x66ocal_length_px\x18\t \x01(\x02\x12\x15\n\rcapture_width\x18\n \x01(\x05\x12\x16\n\x0e\x63\x61pture_height\x18\x0b \x01(\x05\x12\x11\n\tcamera_id\x18\x0c \x01(\t\x12\x18\n\x10\x64istortion_model\x18\r \x01(\tb\x06proto3'
)




_CAMERAINTRINSICS = _descriptor.Descriptor(
  name='CameraIntrinsics',
  full_name='ai.flow.android.CameraIntrinsics',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='ai.flow.android.CameraIntrinsics.timestamp', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='physical_focal_length_mm', full_name='ai.flow.android.CameraIntrinsics.physical_focal_length_mm', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sensor_width_mm', full_name='ai.flow.android.CameraIntrinsics.sensor_width_mm', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sensor_height_mm', full_name='ai.flow.android.CameraIntrinsics.sensor_height_mm', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='active_array_width', full_name='ai.flow.android.CameraIntrinsics.active_array_width', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='active_array_height', full_name='ai.flow.android.CameraIntrinsics.active_array_height', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='distortion_coefficients', full_name='ai.flow.android.CameraIntrinsics.distortion_coefficients', index=6,
      number=7, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='intrinsic_calibration', full_name='ai.flow.android.CameraIntrinsics.intrinsic_calibration', index=7,
      number=8, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='focal_length_px', full_name='ai.flow.android.CameraIntrinsics.focal_length_px', index=8,
      number=9, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='capture_width', full_name='ai.flow.android.CameraIntrinsics.capture_width', index=9,
      number=10, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='capture_height', full_name='ai.flow.android.CameraIntrinsics.capture_height', index=10,
      number=11, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='camera_id', full_name='ai.flow.android.CameraIntrinsics.camera_id', index=11,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='distortion_model', full_name='ai.flow.android.CameraIntrinsics.distortion_model', index=12,
      number=13, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=405,
)

DESCRIPTOR.message_types_by_name['CameraIntrinsics'] = _CAMERAINTRINSICS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CameraIntrinsics = _reflection.GeneratedProtocolMessageType('CameraIntrinsics', (_message.Message,), {
  'DESCRIPTOR' : _CAMERAINTRINSICS,
  '__module__' : 'camera_intrinsics_pb2'
  # @@protoc_insertion_point(class_scope:ai.flow.android.CameraIntrinsics)
  })
_sym_db.RegisterMessage(CameraIntrinsics)


# @@protoc_insertion_point(module_scope)
