# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: imu.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='imu.proto',
  package='ai.flow.android',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\timu.proto\x12\x0f\x61i.flow.android\"\xe9\x01\n\x07IMUData\x12\x11\n\ttimestamp\x18\x01 \x01(\x03\x12\x0f\n\x07\x61\x63\x63\x65l_x\x18\x02 \x01(\x02\x12\x0f\n\x07\x61\x63\x63\x65l_y\x18\x03 \x01(\x02\x12\x0f\n\x07\x61\x63\x63\x65l_z\x18\x04 \x01(\x02\x12\x0e\n\x06gyro_x\x18\x05 \x01(\x02\x12\x0e\n\x06gyro_y\x18\x06 \x01(\x02\x12\x0e\n\x06gyro_z\x18\x07 \x01(\x02\x12\r\n\x05mag_x\x18\x08 \x01(\x02\x12\r\n\x05mag_y\x18\t \x01(\x02\x12\r\n\x05mag_z\x18\n \x01(\x02\x12\x10\n\x08\x61\x63\x63uracy\x18\x0b \x01(\x05\x12\x13\n\x0btemperature\x18\x0c \x01(\x02\x12\x14\n\x0csample_count\x18\r \x01(\x05\x62\x06proto3'
)




_IMUDATA = _descriptor.Descriptor(
  name='IMUData',
  full_name='ai.flow.android.IMUData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='ai.flow.android.IMUData.timestamp', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='accel_x', full_name='ai.flow.android.IMUData.accel_x', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='accel_y', full_name='ai.flow.android.IMUData.accel_y', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='accel_z', full_name='ai.flow.android.IMUData.accel_z', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='gyro_x', full_name='ai.flow.android.IMUData.gyro_x', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='gyro_y', full_name='ai.flow.android.IMUData.gyro_y', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='gyro_z', full_name='ai.flow.android.IMUData.gyro_z', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mag_x', full_name='ai.flow.android.IMUData.mag_x', index=7,
      number=8, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mag_y', full_name='ai.flow.android.IMUData.mag_y', index=8,
      number=9, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mag_z', full_name='ai.flow.android.IMUData.mag_z', index=9,
      number=10, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='accuracy', full_name='ai.flow.android.IMUData.accuracy', index=10,
      number=11, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='temperature', full_name='ai.flow.android.IMUData.temperature', index=11,
      number=12, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sample_count', full_name='ai.flow.android.IMUData.sample_count', index=12,
      number=13, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=264,
)

DESCRIPTOR.message_types_by_name['IMUData'] = _IMUDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

IMUData = _reflection.GeneratedProtocolMessageType('IMUData', (_message.Message,), {
  'DESCRIPTOR' : _IMUDATA,
  '__module__' : 'imu_pb2'
  # @@protoc_insertion_point(class_scope:ai.flow.android.IMUData)
  })
_sym_db.RegisterMessage(IMUData)


# @@protoc_insertion_point(module_scope)
