# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messages.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import camera_pb2 as camera__pb2
import gps_pb2 as gps__pb2
import imu_pb2 as imu__pb2
import can_pb2 as can__pb2
import panda_pb2 as panda__pb2
import camera_intrinsics_pb2 as camera__intrinsics__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='messages.proto',
  package='ai.flow.android',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0emessages.proto\x12\x0f\x61i.flow.android\x1a\x0c\x63\x61mera.proto\x1a\tgps.proto\x1a\timu.proto\x1a\tcan.proto\x1a\x0bpanda.proto\x1a\x17\x63\x61mera_intrinsics.proto\"\xa5\x03\n\nZMQMessage\x12\x11\n\ttimestamp\x18\x01 \x01(\x03\x12\r\n\x05topic\x18\x02 \x01(\t\x12\x34\n\x0c\x63\x61mera_image\x18\x03 \x01(\x0b\x32\x1c.ai.flow.android.CameraImageH\x00\x12\x34\n\x0cgps_location\x18\x05 \x01(\x0b\x32\x1c.ai.flow.android.GPSLocationH\x00\x12,\n\x08gps_data\x18\x06 \x01(\x0b\x32\x18.ai.flow.android.GPSDataH\x00\x12,\n\x08imu_data\x18\x07 \x01(\x0b\x32\x18.ai.flow.android.IMUDataH\x00\x12,\n\x08\x63\x61n_data\x18\x0b \x01(\x0b\x32\x18.ai.flow.android.CANDataH\x00\x12\x34\n\x0cpanda_health\x18\x0c \x01(\x0b\x32\x1c.ai.flow.android.PandaHealthH\x00\x12>\n\x11\x63\x61mera_intrinsics\x18\r \x01(\x0b\x32!.ai.flow.android.CameraIntrinsicsH\x00\x42\t\n\x07payloadb\x06proto3'
  ,
  dependencies=[camera__pb2.DESCRIPTOR,gps__pb2.DESCRIPTOR,imu__pb2.DESCRIPTOR,can__pb2.DESCRIPTOR,panda__pb2.DESCRIPTOR,camera__intrinsics__pb2.DESCRIPTOR,])




_ZMQMESSAGE = _descriptor.Descriptor(
  name='ZMQMessage',
  full_name='ai.flow.android.ZMQMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='ai.flow.android.ZMQMessage.timestamp', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='topic', full_name='ai.flow.android.ZMQMessage.topic', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='camera_image', full_name='ai.flow.android.ZMQMessage.camera_image', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='gps_location', full_name='ai.flow.android.ZMQMessage.gps_location', index=3,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='gps_data', full_name='ai.flow.android.ZMQMessage.gps_data', index=4,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='imu_data', full_name='ai.flow.android.ZMQMessage.imu_data', index=5,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='can_data', full_name='ai.flow.android.ZMQMessage.can_data', index=6,
      number=11, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='panda_health', full_name='ai.flow.android.ZMQMessage.panda_health', index=7,
      number=12, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='camera_intrinsics', full_name='ai.flow.android.ZMQMessage.camera_intrinsics', index=8,
      number=13, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='payload', full_name='ai.flow.android.ZMQMessage.payload',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=121,
  serialized_end=542,
)

_ZMQMESSAGE.fields_by_name['camera_image'].message_type = camera__pb2._CAMERAIMAGE
_ZMQMESSAGE.fields_by_name['gps_location'].message_type = gps__pb2._GPSLOCATION
_ZMQMESSAGE.fields_by_name['gps_data'].message_type = gps__pb2._GPSDATA
_ZMQMESSAGE.fields_by_name['imu_data'].message_type = imu__pb2._IMUDATA
_ZMQMESSAGE.fields_by_name['can_data'].message_type = can__pb2._CANDATA
_ZMQMESSAGE.fields_by_name['panda_health'].message_type = panda__pb2._PANDAHEALTH
_ZMQMESSAGE.fields_by_name['camera_intrinsics'].message_type = camera__intrinsics__pb2._CAMERAINTRINSICS
_ZMQMESSAGE.oneofs_by_name['payload'].fields.append(
  _ZMQMESSAGE.fields_by_name['camera_image'])
_ZMQMESSAGE.fields_by_name['camera_image'].containing_oneof = _ZMQMESSAGE.oneofs_by_name['payload']
_ZMQMESSAGE.oneofs_by_name['payload'].fields.append(
  _ZMQMESSAGE.fields_by_name['gps_location'])
_ZMQMESSAGE.fields_by_name['gps_location'].containing_oneof = _ZMQMESSAGE.oneofs_by_name['payload']
_ZMQMESSAGE.oneofs_by_name['payload'].fields.append(
  _ZMQMESSAGE.fields_by_name['gps_data'])
_ZMQMESSAGE.fields_by_name['gps_data'].containing_oneof = _ZMQMESSAGE.oneofs_by_name['payload']
_ZMQMESSAGE.oneofs_by_name['payload'].fields.append(
  _ZMQMESSAGE.fields_by_name['imu_data'])
_ZMQMESSAGE.fields_by_name['imu_data'].containing_oneof = _ZMQMESSAGE.oneofs_by_name['payload']
_ZMQMESSAGE.oneofs_by_name['payload'].fields.append(
  _ZMQMESSAGE.fields_by_name['can_data'])
_ZMQMESSAGE.fields_by_name['can_data'].containing_oneof = _ZMQMESSAGE.oneofs_by_name['payload']
_ZMQMESSAGE.oneofs_by_name['payload'].fields.append(
  _ZMQMESSAGE.fields_by_name['panda_health'])
_ZMQMESSAGE.fields_by_name['panda_health'].containing_oneof = _ZMQMESSAGE.oneofs_by_name['payload']
_ZMQMESSAGE.oneofs_by_name['payload'].fields.append(
  _ZMQMESSAGE.fields_by_name['camera_intrinsics'])
_ZMQMESSAGE.fields_by_name['camera_intrinsics'].containing_oneof = _ZMQMESSAGE.oneofs_by_name['payload']
DESCRIPTOR.message_types_by_name['ZMQMessage'] = _ZMQMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ZMQMessage = _reflection.GeneratedProtocolMessageType('ZMQMessage', (_message.Message,), {
  'DESCRIPTOR' : _ZMQMESSAGE,
  '__module__' : 'messages_pb2'
  # @@protoc_insertion_point(class_scope:ai.flow.android.ZMQMessage)
  })
_sym_db.RegisterMessage(ZMQMessage)


# @@protoc_insertion_point(module_scope)
