# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: panda.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='panda.proto',
  package='ai.flow.android',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0bpanda.proto\x12\x0f\x61i.flow.android\"\xe8\x04\n\x0bPandaHealth\x12\x11\n\ttimestamp\x18\x01 \x01(\x03\x12\x12\n\nuptime_pkt\x18\x02 \x01(\r\x12\x18\n\x10\x63ontrols_allowed\x18\x03 \x01(\x08\x12\x13\n\x0bsafety_mode\x18\x04 \x01(\r\x12\x14\n\x0csafety_param\x18\x05 \x01(\r\x12\x14\n\x0c\x66\x61ult_status\x18\x06 \x01(\r\x12\x12\n\nvoltage_mv\x18\x07 \x01(\r\x12\x12\n\ncurrent_ma\x18\x08 \x01(\r\x12\x1a\n\x12power_save_enabled\x18\t \x01(\x08\x12\x12\n\ntx_blocked\x18\n \x01(\r\x12\x13\n\x0btx_overflow\x18\x0b \x01(\r\x12\x12\n\nrx_invalid\x18\x0c \x01(\r\x12\x13\n\x0brx_overflow\x18\r \x01(\r\x12\x19\n\x11rx_checks_invalid\x18\x0e \x01(\r\x12\x12\n\nfaults_pkt\x18\x0f \x01(\r\x12\x17\n\x0fspi_error_count\x18\x10 \x01(\r\x12\x15\n\rignition_line\x18\x11 \x01(\x08\x12\x14\n\x0cignition_can\x18\x12 \x01(\x08\x12\x1a\n\x12\x63\x61r_harness_status\x18\x13 \x01(\r\x12\x16\n\x0eheartbeat_lost\x18\x14 \x01(\x08\x12\x1e\n\x16\x61lternative_experience\x18\x15 \x01(\r\x12\x16\n\x0einterrupt_load\x18\x16 \x01(\x02\x12\x11\n\tfan_power\x18\x17 \x01(\r\x12\x17\n\x0fsbu1_voltage_mv\x18\x18 \x01(\r\x12\x17\n\x0fsbu2_voltage_mv\x18\x19 \x01(\r\x12\x1b\n\x13som_reset_triggered\x18\x1a \x01(\x08\x62\x06proto3'
)




_PANDAHEALTH = _descriptor.Descriptor(
  name='PandaHealth',
  full_name='ai.flow.android.PandaHealth',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='ai.flow.android.PandaHealth.timestamp', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='uptime_pkt', full_name='ai.flow.android.PandaHealth.uptime_pkt', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='controls_allowed', full_name='ai.flow.android.PandaHealth.controls_allowed', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='safety_mode', full_name='ai.flow.android.PandaHealth.safety_mode', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='safety_param', full_name='ai.flow.android.PandaHealth.safety_param', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='fault_status', full_name='ai.flow.android.PandaHealth.fault_status', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='voltage_mv', full_name='ai.flow.android.PandaHealth.voltage_mv', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='current_ma', full_name='ai.flow.android.PandaHealth.current_ma', index=7,
      number=8, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='power_save_enabled', full_name='ai.flow.android.PandaHealth.power_save_enabled', index=8,
      number=9, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tx_blocked', full_name='ai.flow.android.PandaHealth.tx_blocked', index=9,
      number=10, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tx_overflow', full_name='ai.flow.android.PandaHealth.tx_overflow', index=10,
      number=11, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='rx_invalid', full_name='ai.flow.android.PandaHealth.rx_invalid', index=11,
      number=12, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='rx_overflow', full_name='ai.flow.android.PandaHealth.rx_overflow', index=12,
      number=13, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='rx_checks_invalid', full_name='ai.flow.android.PandaHealth.rx_checks_invalid', index=13,
      number=14, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='faults_pkt', full_name='ai.flow.android.PandaHealth.faults_pkt', index=14,
      number=15, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='spi_error_count', full_name='ai.flow.android.PandaHealth.spi_error_count', index=15,
      number=16, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ignition_line', full_name='ai.flow.android.PandaHealth.ignition_line', index=16,
      number=17, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ignition_can', full_name='ai.flow.android.PandaHealth.ignition_can', index=17,
      number=18, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='car_harness_status', full_name='ai.flow.android.PandaHealth.car_harness_status', index=18,
      number=19, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='heartbeat_lost', full_name='ai.flow.android.PandaHealth.heartbeat_lost', index=19,
      number=20, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='alternative_experience', full_name='ai.flow.android.PandaHealth.alternative_experience', index=20,
      number=21, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='interrupt_load', full_name='ai.flow.android.PandaHealth.interrupt_load', index=21,
      number=22, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='fan_power', full_name='ai.flow.android.PandaHealth.fan_power', index=22,
      number=23, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sbu1_voltage_mv', full_name='ai.flow.android.PandaHealth.sbu1_voltage_mv', index=23,
      number=24, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sbu2_voltage_mv', full_name='ai.flow.android.PandaHealth.sbu2_voltage_mv', index=24,
      number=25, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='som_reset_triggered', full_name='ai.flow.android.PandaHealth.som_reset_triggered', index=25,
      number=26, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=649,
)

DESCRIPTOR.message_types_by_name['PandaHealth'] = _PANDAHEALTH
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PandaHealth = _reflection.GeneratedProtocolMessageType('PandaHealth', (_message.Message,), {
  'DESCRIPTOR' : _PANDAHEALTH,
  '__module__' : 'panda_pb2'
  # @@protoc_insertion_point(class_scope:ai.flow.android.PandaHealth)
  })
_sym_db.RegisterMessage(PandaHealth)


# @@protoc_insertion_point(module_scope)
