# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: camera_calib.proto
"""Generated protocol buffer code."""

from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x12\x63\x61mera_calib.proto\x12\x0c\x61i.flow.adas"\xaf\x02\n\x16\x43\x61meraCalibrationState\x12\x11\n\ttimestamp\x18\x01 \x01(\x03\x12\x10\n\x08roll_deg\x18\x02 \x01(\x01\x12\x11\n\tpitch_deg\x18\x03 \x01(\x01\x12\x0f\n\x07yaw_deg\x18\x04 \x01(\x01\x12\x17\n\x0f\x63\x61mera_height_m\x18\x05 \x01(\x01\x12\n\n\x02\x66x\x18\x06 \x01(\x01\x12\n\n\x02\x66y\x18\x07 \x01(\x01\x12\n\n\x02\x63x\x18\x08 \x01(\x01\x12\n\n\x02\x63y\x18\t \x01(\x01\x12\x1b\n\x13\x63\x61libration_success\x18\n \x01(\x08\x12\x11\n\tn_updates\x18\x0b \x01(\x05\x12\x0c\n\x04vp_u\x18\x0c \x01(\x01\x12\x0c\n\x04vp_v\x18\r \x01(\x01\x12\x0e\n\x06has_vp\x18\x0e \x01(\x08\x12\x13\n\x0b\x63\x61l_percent\x18\x0f \x01(\x05\x12\x12\n\ncal_status\x18\x10 \x01(\x05"#\n\x0bLaneUvPoint\x12\t\n\x01u\x18\x01 \x01(\x01\x12\t\n\x01v\x18\x02 \x01(\x01"t\n\x06LaneUv\x12\x11\n\ttimestamp\x18\x01 \x01(\x03\x12*\n\x07left_uv\x18\x02 \x03(\x0b\x32\x19.ai.flow.adas.LaneUvPoint\x12+\n\x08right_uv\x18\x03 \x03(\x0b\x32\x19.ai.flow.adas.LaneUvPoint"u\n\x0e\x43\x61meraOdometry\x12\x11\n\ttimestamp\x18\x01 \x01(\x03\x12\r\n\x05trans\x18\x02 \x03(\x02\x12\x0b\n\x03rot\x18\x03 \x03(\x02\x12\x11\n\ttrans_std\x18\x04 \x03(\x02\x12\x0f\n\x07rot_std\x18\x05 \x03(\x02\x12\x10\n\x08\x66rame_id\x18\x06 \x01(\x05\x42\x12\x42\x10\x43\x61meraCalibOuterb\x06proto3'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "camera_calib_pb2", globals())
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    DESCRIPTOR._serialized_options = b"B\020CameraCalibOuter"
    _CAMERACALIBRATIONSTATE._serialized_start = 37
    _CAMERACALIBRATIONSTATE._serialized_end = 340
    _LANEUVPOINT._serialized_start = 342
    _LANEUVPOINT._serialized_end = 377
    _LANEUV._serialized_start = 379
    _LANEUV._serialized_end = 495
    _CAMERAODOMETRY._serialized_start = 497
    _CAMERAODOMETRY._serialized_end = 614
# @@protoc_insertion_point(module_scope)
