# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: camera_intrinsics.proto
"""Generated protocol buffer code."""

from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x17\x63\x61mera_intrinsics.proto\x12\x0c\x61i.flow.adas"\xe8\x02\n\x10\x43\x61meraIntrinsics\x12\x11\n\ttimestamp\x18\x01 \x01(\x03\x12 \n\x18physical_focal_length_mm\x18\x02 \x01(\x02\x12\x17\n\x0fsensor_width_mm\x18\x03 \x01(\x02\x12\x18\n\x10sensor_height_mm\x18\x04 \x01(\x02\x12\x1a\n\x12\x61\x63tive_array_width\x18\x05 \x01(\x05\x12\x1b\n\x13\x61\x63tive_array_height\x18\x06 \x01(\x05\x12\x1f\n\x17\x64istortion_coefficients\x18\x07 \x03(\x02\x12\x1d\n\x15intrinsic_calibration\x18\x08 \x03(\x02\x12\x17\n\x0f\x66ocal_length_px\x18\t \x01(\x02\x12\x15\n\rcapture_width\x18\n \x01(\x05\x12\x16\n\x0e\x63\x61pture_height\x18\x0b \x01(\x05\x12\x11\n\tcamera_id\x18\x0c \x01(\t\x12\x18\n\x10\x64istortion_model\x18\r \x01(\tb\x06proto3'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "camera_intrinsics_pb2", globals())
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    _CAMERAINTRINSICS._serialized_start = 42
    _CAMERAINTRINSICS._serialized_end = 402
# @@protoc_insertion_point(module_scope)
