# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gps.proto
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\tgps.proto\x12\x0c\x61i.flow.adas"\x83\x03\n\x0bGPSLocation\x12\x11\n\ttimestamp\x18\x01 \x01(\x03\x12\x10\n\x08latitude\x18\x02 \x01(\x01\x12\x11\n\tlongitude\x18\x03 \x01(\x01\x12\x10\n\x08\x61ltitude\x18\x04 \x01(\x01\x12\x1b\n\x13horizontal_accuracy\x18\x05 \x01(\x02\x12\x19\n\x11vertical_accuracy\x18\x06 \x01(\x02\x12\r\n\x05speed\x18\x07 \x01(\x02\x12\x0f\n\x07\x62\x65\x61ring\x18\x08 \x01(\x02\x12\x17\n\x0fsatellites_used\x18\t \x01(\x05\x12\x0c\n\x04hdop\x18\n \x01(\x02\x12\x0c\n\x04vdop\x18\x0b \x01(\x02\x12\x33\n\x08\x66ix_type\x18\x0c \x01(\x0e\x32!.ai.flow.adas.GPSLocation.FixType"h\n\x07\x46ixType\x12\n\n\x06NO_FIX\x10\x00\x12\x12\n\x0e\x44\x45\x41\x44_RECKONING\x10\x01\x12\n\n\x06\x46IX_2D\x10\x02\x12\n\n\x06\x46IX_3D\x10\x03\x12\x16\n\x12GPS_DEAD_RECKONING\x10\x04\x12\r\n\tTIME_ONLY\x10\x05"\x9c\x01\n\x07GPSData\x12\x11\n\ttimestamp\x18\x01 \x01(\x03\x12\x10\n\x08latitude\x18\x02 \x01(\x01\x12\x11\n\tlongitude\x18\x03 \x01(\x01\x12\x10\n\x08\x61ltitude\x18\x04 \x01(\x01\x12\r\n\x05speed\x18\x05 \x01(\x02\x12\x0f\n\x07\x62\x65\x61ring\x18\x06 \x01(\x02\x12\x15\n\rgps_timestamp\x18\x07 \x01(\x03\x12\x10\n\x08provider\x18\x08 \x01(\tb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "gps_pb2", _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _globals["_GPSLOCATION"]._serialized_start = 28
    _globals["_GPSLOCATION"]._serialized_end = 415
    _globals["_GPSLOCATION_FIXTYPE"]._serialized_start = 311
    _globals["_GPSLOCATION_FIXTYPE"]._serialized_end = 415
    _globals["_GPSDATA"]._serialized_start = 418
    _globals["_GPSDATA"]._serialized_end = 574
# @@protoc_insertion_point(module_scope)
