# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: imu.proto
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\timu.proto\x12\x0c\x61i.flow.adas"\xe9\x01\n\x07IMUData\x12\x11\n\ttimestamp\x18\x01 \x01(\x03\x12\x0f\n\x07\x61\x63\x63\x65l_x\x18\x02 \x01(\x02\x12\x0f\n\x07\x61\x63\x63\x65l_y\x18\x03 \x01(\x02\x12\x0f\n\x07\x61\x63\x63\x65l_z\x18\x04 \x01(\x02\x12\x0e\n\x06gyro_x\x18\x05 \x01(\x02\x12\x0e\n\x06gyro_y\x18\x06 \x01(\x02\x12\x0e\n\x06gyro_z\x18\x07 \x01(\x02\x12\r\n\x05mag_x\x18\x08 \x01(\x02\x12\r\n\x05mag_y\x18\t \x01(\x02\x12\r\n\x05mag_z\x18\n \x01(\x02\x12\x10\n\x08\x61\x63\x63uracy\x18\x0b \x01(\x05\x12\x13\n\x0btemperature\x18\x0c \x01(\x02\x12\x14\n\x0csample_count\x18\r \x01(\x05\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "imu_pb2", _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _globals["_IMUDATA"]._serialized_start = 28
    _globals["_IMUDATA"]._serialized_end = 261
# @@protoc_insertion_point(module_scope)
