# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lane_keep.proto
"""Generated protocol buffer code."""

from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0flane_keep.proto\x12\x0c\x61i.flow.adas"\xda\x01\n\rLaneKeepState\x12\x11\n\ttimestamp\x18\x01 \x01(\x03\x12\x11\n\tsteer_rad\x18\x02 \x01(\x01\x12\x12\n\nsteer_norm\x18\x03 \x01(\x01\x12\x10\n\x08throttle\x18\x04 \x01(\x01\x12\r\n\x05\x62rake\x18\x05 \x01(\x01\x12\x13\n\x0blookahead_m\x18\x06 \x01(\x01\x12\x10\n\x08target_x\x18\x07 \x01(\x01\x12\x10\n\x08target_y\x18\x08 \x01(\x01\x12\x12\n\nhas_target\x18\t \x01(\x08\x12\x11\n\tcurvature\x18\n \x01(\x01\x12\x0e\n\x06status\x18\x0b \x01(\tB\x0f\x42\rLaneKeepOuterb\x06proto3'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "lane_keep_pb2", globals())
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    DESCRIPTOR._serialized_options = b"B\rLaneKeepOuter"
    _LANEKEEPSTATE._serialized_start = 34
    _LANEKEEPSTATE._serialized_end = 252
# @@protoc_insertion_point(module_scope)
