# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: localization.proto
"""Generated protocol buffer code."""

from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x12localization.proto\x12\x0c\x61i.flow.adas"\xa3\x01\n\x10LocalizationPose\x12\x11\n\ttimestamp\x18\x01 \x01(\x03\x12\t\n\x01x\x18\x02 \x01(\x01\x12\t\n\x01y\x18\x03 \x01(\x01\x12\x0b\n\x03yaw\x18\x04 \x01(\x01\x12\t\n\x01v\x18\x05 \x01(\x01\x12\x10\n\x08yaw_rate\x18\x06 \x01(\x01\x12\x0e\n\x06odom_x\x18\x07 \x01(\x01\x12\x0e\n\x06odom_y\x18\x08 \x01(\x01\x12\r\n\x05\x65kf_x\x18\t \x01(\x01\x12\r\n\x05\x65kf_y\x18\n \x01(\x01\x42\x13\x42\x11LocalizationOuterb\x06proto3'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "localization_pb2", globals())
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    DESCRIPTOR._serialized_options = b"B\021LocalizationOuter"
    _LOCALIZATIONPOSE._serialized_start = 37
    _LOCALIZATIONPOSE._serialized_end = 200
# @@protoc_insertion_point(module_scope)
