# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messages.proto
"""Generated protocol buffer code."""

from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import camera_pb2 as camera__pb2
import gps_pb2 as gps__pb2
import imu_pb2 as imu__pb2
import can_pb2 as can__pb2
import panda_pb2 as panda__pb2
import camera_intrinsics_pb2 as camera__intrinsics__pb2
import lanes_pb2 as lanes__pb2
import car_state_pb2 as car__state__pb2
import steer_pb2 as steer__pb2
import lane_keep_pb2 as lane__keep__pb2
import localization_pb2 as localization__pb2
import camera_calib_pb2 as camera__calib__pb2

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b"\n\x0emessages.proto\x12\x0c\x61i.flow.adas\x1a\x0c\x63\x61mera.proto\x1a\tgps.proto\x1a\timu.proto\x1a\tcan.proto\x1a\x0bpanda.proto\x1a\x17\x63\x61mera_intrinsics.proto\x1a\x0blanes.proto\x1a\x0f\x63\x61r_state.proto\x1a\x0bsteer.proto\x1a\x0flane_keep.proto\x1a\x12localization.proto\x1a\x12\x63\x61mera_calib.proto\"\xb0\x06\n\nZMQMessage\x12\x11\n\ttimestamp\x18\x01 \x01(\x03\x12\r\n\x05topic\x18\x02 \x01(\t\x12\x31\n\x0c\x63\x61mera_image\x18\x03 \x01(\x0b\x32\x19.ai.flow.adas.CameraImageH\x00\x12\x31\n\x0cgps_location\x18\x05 \x01(\x0b\x32\x19.ai.flow.adas.GPSLocationH\x00\x12)\n\x08gps_data\x18\x06 \x01(\x0b\x32\x15.ai.flow.adas.GPSDataH\x00\x12)\n\x08imu_data\x18\x07 \x01(\x0b\x32\x15.ai.flow.adas.IMUDataH\x00\x12)\n\x08\x63\x61n_data\x18\x0b \x01(\x0b\x32\x15.ai.flow.adas.CANDataH\x00\x12\x31\n\x0cpanda_health\x18\x0c \x01(\x0b\x32\x19.ai.flow.adas.PandaHealthH\x00\x12;\n\x11\x63\x61mera_intrinsics\x18\r \x01(\x0b\x32\x1e.ai.flow.adas.CameraIntrinsicsH\x00\x12-\n\nlane_lines\x18\x0e \x01(\x0b\x32\x17.ai.flow.adas.LaneLinesH\x00\x12+\n\tcar_state\x18\x0f \x01(\x0b\x32\x16.ai.flow.adas.CarStateH\x00\x12\x33\n\rsteer_command\x18\x10 \x01(\x0b\x32\x1a.ai.flow.adas.SteerCommandH\x00\x12\x30\n\tlane_keep\x18\x11 \x01(\x0b\x32\x1b.ai.flow.adas.LaneKeepStateH\x00\x12;\n\x11localization_pose\x18\x12 \x01(\x0b\x32\x1e.ai.flow.adas.LocalizationPoseH\x00\x12<\n\x0c\x63\x61mera_calib\x18\x13 \x01(\x0b\x32$.ai.flow.adas.CameraCalibrationStateH\x00\x12'\n\x07lane_uv\x18\x14 \x01(\x0b\x32\x14.ai.flow.adas.LaneUvH\x00\x12\x37\n\x0f\x63\x61mera_odometry\x18\x15 \x01(\x0b\x32\x1c.ai.flow.adas.CameraOdometryH\x00\x42\t\n\x07payloadb\x06proto3"
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "messages_pb2", globals())
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    _ZMQMESSAGE._serialized_start = 218
    _ZMQMESSAGE._serialized_end = 1034
# @@protoc_insertion_point(module_scope)
