# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: panda.proto
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0bpanda.proto\x12\x0c\x61i.flow.adas"\xe8\x04\n\x0bPandaHealth\x12\x11\n\ttimestamp\x18\x01 \x01(\x03\x12\x12\n\nuptime_pkt\x18\x02 \x01(\r\x12\x18\n\x10\x63ontrols_allowed\x18\x03 \x01(\x08\x12\x13\n\x0bsafety_mode\x18\x04 \x01(\r\x12\x14\n\x0csafety_param\x18\x05 \x01(\r\x12\x14\n\x0c\x66\x61ult_status\x18\x06 \x01(\r\x12\x12\n\nvoltage_mv\x18\x07 \x01(\r\x12\x12\n\ncurrent_ma\x18\x08 \x01(\r\x12\x1a\n\x12power_save_enabled\x18\t \x01(\x08\x12\x12\n\ntx_blocked\x18\n \x01(\r\x12\x13\n\x0btx_overflow\x18\x0b \x01(\r\x12\x12\n\nrx_invalid\x18\x0c \x01(\r\x12\x13\n\x0brx_overflow\x18\r \x01(\r\x12\x19\n\x11rx_checks_invalid\x18\x0e \x01(\r\x12\x12\n\nfaults_pkt\x18\x0f \x01(\r\x12\x17\n\x0fspi_error_count\x18\x10 \x01(\r\x12\x15\n\rignition_line\x18\x11 \x01(\x08\x12\x14\n\x0cignition_can\x18\x12 \x01(\x08\x12\x1a\n\x12\x63\x61r_harness_status\x18\x13 \x01(\r\x12\x16\n\x0eheartbeat_lost\x18\x14 \x01(\x08\x12\x1e\n\x16\x61lternative_experience\x18\x15 \x01(\r\x12\x16\n\x0einterrupt_load\x18\x16 \x01(\x02\x12\x11\n\tfan_power\x18\x17 \x01(\r\x12\x17\n\x0fsbu1_voltage_mv\x18\x18 \x01(\r\x12\x17\n\x0fsbu2_voltage_mv\x18\x19 \x01(\r\x12\x1b\n\x13som_reset_triggered\x18\x1a \x01(\x08\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "panda_pb2", _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _globals["_PANDAHEALTH"]._serialized_start = 30
    _globals["_PANDAHEALTH"]._serialized_end = 646
# @@protoc_insertion_point(module_scope)
