version: "3"
services:
  dev_container:
    container_name: dev_container
    build:
      context: .
      network: host
      dockerfile: Dockerfile
      args:
        USERNAME: ${USER:-user}
        USER_UID: ${UID:-1000}
        USER_GID: ${GID:-1000}
    extra_hosts:
      - "registry.int.e-kama.com:10.124.1.143"
      - "gitlab.int.e-kama.com:10.124.1.143"
    volumes:
      - ~/:/workspace
      - ~/.ssh:/home/${USER:-user}/.ssh
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ~/.Xauthority:/home/${USER:-user}/.Xauthority:rw
    network_mode: "host"
    restart: always
    tty: true
    ipc: host
    working_dir: /workspace
    environment:
      - DISPLAY=${DISPLAY}
      - USERNAME=${USER:-user}
      - USER_UID=${UID:-1000}
      - USER_GID=${GID:-1000}
